# version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: task-app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: task-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: task-db
    restart: always
    environment:
      MYSQL_DATABASE: task_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33066:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
